version: '3.1'

services:

  tg:
    build: .
    restart: always
    container_name: tg
    networks:
      - app-network
    depends_on:
      - db
    command: sh -c 'alembic upgrade head && python -m src'

  db:
    image: postgres
    restart: always
    container_name: db
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
    ports:
      - '5400:5432'

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks:
      - app-network
    ports:
      - '8080:8080'

volumes:
  postgres_data: null

networks:
  app-network: null
